name: Build and Deploy Docker Container
run-name: ${{ gitea.actor }}
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0
      
      - name: Docker Metadata action
        id: metadata
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            git.jmn.au/${{ gitea.repository }}
          tags: |
            type=raw,latest
                      
      - name: Login to Container Repository
        uses: docker/login-action@v3
        with:
          registry: git.jmn.au
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.PKG_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: VERSION=${{ steps.version.outputs.version }}